# Part 4 : Intro to NumPy

##### NumPy is the fundamental package for scientitific computing with Python. It countains among other things:
- a powerful N-dimensional array object
- sophisticated (brooadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

### Import some lbries

In [5]:
import sys
import numpy as np

### How Binari work

Classic in HighSchool.
The higher the number is, more bit you will need. 

In [23]:
n = 3
2 ** n

8

In [28]:
2 ** 7

128

In Numpy, you can choose the number of bit that a number can have.

In [35]:
np.int8
np.int32

numpy.int32

### Basic Numpy Arrays

In [38]:
np.array([1, 2, 3])

array([1, 2, 3])

In [59]:
a = np.array([1, 2, 3, 4])
b = np.array([0., 0.5, 1., 1.5, 2.])
a[0:]

array([1, 2, 3, 4])

In [50]:
a[::2]

array([1, 3])

In [52]:
a[1:-1]

array([2, 3])

### Array Type

In [55]:
a

array([1, 2, 3, 4])

In [57]:
a.dtype

dtype('int32')

In [61]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [63]:
b.dtype

dtype('float64')

In [71]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [73]:
c = np.array(['a', 'b', 'c'])

In [75]:
c.dtype

dtype('<U1')

In [85]:
d = np.array([{'a':1}, sys])

In [87]:
d.dtype

dtype('O')

### Dimension and shapes

In [90]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [92]:
A.shape

(2, 3)

In [94]:
A.ndim

2

In [96]:
A.size

6

In [99]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [101]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [103]:
B.shape

(2, 2, 3)

In [105]:
B.ndim

3

In [107]:
B.size

12

If the shape isn't consistent, it will just fall back to regular Python objects:

In [174]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [176]:
C.dtype

NameError: name 'C' is not defined

### Indexing and Slicing of Matrices

In [122]:
# Sqaure matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [124]:
A[0]

array([1, 2, 3])

In [126]:
A[1][0]

4

In [128]:
A[1, 0]

4

In [132]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [136]:
A[2:, 2:]

array([[9]])

### Summary statistics

In [139]:
a = np.array([1, 2, 3, 4])

In [141]:
a.sum()

10

In [143]:
a.mean()

2.5

In [145]:
a.std()

1.118033988749895

In [147]:
a.var()

1.25

In [163]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [165]:
A.sum(axis=0)

array([12, 15, 18])

In [167]:
A.sum(axis=1)

array([ 6, 15, 24])

In [171]:
A.mean(axis=1)

array([2., 5., 8.])

### Braodcasting and Vectorized operations

In [202]:
a = np.arange(4)

In [204]:
a

array([0, 1, 2, 3])

In [206]:
a + 10

array([10, 11, 12, 13])

In [208]:
a * 10

array([ 0, 10, 20, 30])

In [210]:
a

array([0, 1, 2, 3])

In [212]:
a += 100

In [214]:
a

array([100, 101, 102, 103])

In [216]:
l = [0, 1, 2, 3]

In [218]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [220]:
a = np.arange(4)

In [222]:
a

array([0, 1, 2, 3])

In [224]:
b = np.array([10, 10, 10, 10])

In [226]:
a + b

array([10, 11, 12, 13])

In [228]:
a * b

array([ 0, 10, 20, 30])

### Boolean arrays

In [45]:
a = np.arange(4)

In [47]:
a

array([0, 1, 2, 3])

In [49]:
a[[0, -1]]

array([0, 3])

In [51]:
a[[True, False, False, True]]

array([0, 3])

In [53]:
a >= 2

array([False, False,  True,  True])

In [55]:
a[a >= 2]

array([2, 3])

In [57]:
a.mean()

1.5

In [59]:
a[a > a.mean()]

array([2, 3])

In [61]:
a[~(a > a.mean())]

array([0, 1])

In [63]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [65]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [67]:
A = np.random.randint(100, size=(3, 3))

In [69]:
A

array([[86, 96, 11],
       [33, 12, 91],
       [25, 98, 28]])

In [73]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([86, 11, 12, 25, 28])

In [75]:
A > 30

array([[ True,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [77]:
A[A > 30]

array([86, 96, 33, 91, 98])

### Linear Algebra

In [94]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [96]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [98]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [100]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [102]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [104]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

### Size of objects in Memory
#### Int, Floats

In [109]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [111]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [113]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [135]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [115]:
np.dtype(float).itemsize

8

#### Lists are even larger

In [120]:
# A on-element list
sys.getsizeof([1])

64

In [122]:
# An array of one element in Numpy
np.array([1]).nbytes

4

#### And performance is also important

In [161]:
l = list(range(1000000))

In [163]:
a = np.arange(1000000)

In [165]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 3.54 ms


584144992

In [167]:
%time sum( [x ** 2 for x in l])

CPU times: total: 156 ms
Wall time: 171 ms


333332833333500000

### Useful Numpy functions

#### random

In [171]:
np.random.random(size=2)

array([0.69805126, 0.51778793])

In [173]:
np.random.normal(size=2)

array([-0.29191327,  0.16882915])

In [175]:
np.random.rand(2, 4)

array([[0.35157806, 0.62176088, 0.37514958, 0.07214692],
       [0.20843831, 0.09298244, 0.44854882, 0.31951262]])

#### arange

In [178]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [182]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### reshape

In [187]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [189]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### linspace

In [192]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [194]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [196]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

#### zeros, ones, empty

In [201]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [203]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [207]:
np.zeros((3, 3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [209]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [211]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [217]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [219]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])